#ifndef GAME_SERVER_FOXNET_COSMETICS_TYPES_H
#define GAME_SERVER_FOXNET_COSMETICS_TYPES_H

enum
{
	TRAILTYPE_NONE = 0,
	TRAILTYPE_STAR = 1,
	TRAILTYPE_DOT = 2,
};

enum
{
	DEATHTYPE_NONE = 0,
	DEATHTYPE_EXPLOSION = 1,
	DEATHTYPE_HAMMERHIT = 2,
	DEATHTYPE_DAMAGEIND = 3,
	DEATHTYPE_LASER = 4,
};

enum
{
	HATTYPE_NONE = 0,
	HATTYPE_HAMMER = 1,
	HATTYPE_GUN = 2,
	HATTYPE_SHOTGUN = 3,
	HATTYPE_GRENADE = 4,
	HATTYPE_LASER = 5,
	HATTYPE_NINJA = 6,
	HATTYPE_PARTY = 7,
	HATTYPE_TOPHAT = 8,
	HATTYPE_HEART = 9,
};

#endif // GAME_SERVER_FOXNET_COSMETICS_TYPES_H
